CREATE TABLE `stock_price_ranking` (
                                       `id` int NOT NULL AUTO_INCREMENT,
                                       `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
                                       `stock_code` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '代码',
                                       `stock_name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '名称',
                                       `curent_price` float DEFAULT NULL COMMENT '最新',
                                       `increase_precent` float DEFAULT NULL COMMENT '涨幅',
                                       `quantum_total` float DEFAULT NULL COMMENT '总量',
                                       `quantum_current` float DEFAULT NULL COMMENT '现量',
                                       `buy_price` float DEFAULT NULL COMMENT '买入价',
                                       `sell_price` float DEFAULT NULL COMMENT '卖出价',
                                       `increase_speed` float DEFAULT NULL COMMENT '涨速',
                                       `turnover` float DEFAULT NULL COMMENT '换手',
                                       `amount` float DEFAULT NULL COMMENT '金额',
                                       `pe` float DEFAULT NULL COMMENT '市盈率',
                                       `subordinate` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '所属行业',
                                       `highest` float DEFAULT NULL COMMENT '最高',
                                       `minimum` float DEFAULT NULL COMMENT '最低',
                                       `open_price` float DEFAULT NULL COMMENT '开盘',
                                       `yesterday_close_price` float DEFAULT NULL COMMENT '昨收',
                                       `amplitude` float DEFAULT NULL COMMENT '振幅',
                                       `appoint` float DEFAULT NULL COMMENT '量比',
                                       `magnitude` float DEFAULT NULL COMMENT '委比',
                                       `committee` float DEFAULT NULL COMMENT '委差',
                                       `average` float DEFAULT NULL COMMENT '均价',
                                       `inside_dish` float DEFAULT NULL COMMENT '内盘',
                                       `outside_dish` float DEFAULT NULL COMMENT '外盘',
                                       `side_than` float DEFAULT NULL COMMENT '内外比',
                                       `buy_quantity` float DEFAULT NULL COMMENT '买一量',
                                       `sell_quantity` float DEFAULT NULL COMMENT '卖一量',
                                       `price_to_book` float DEFAULT NULL COMMENT '市净率',
                                       `total_equity` float DEFAULT NULL COMMENT '总股本',
                                       `total_market_value` float DEFAULT NULL COMMENT '总市值',
                                       `circulation_capital` float DEFAULT NULL COMMENT '流通股本',
                                       `current_market` float DEFAULT NULL COMMENT '流通市值',
                                       `three_days_up` float DEFAULT NULL COMMENT '3日涨幅',
                                       `six_days_up` float DEFAULT NULL COMMENT '6日涨幅',
                                       `three_days_change` float DEFAULT NULL COMMENT '3日换手',
                                       `six_days_change` float DEFAULT NULL COMMENT '6日换手',
                                       `even_number_days` float DEFAULT NULL COMMENT '连涨天数',
                                       `up_this_month` float DEFAULT NULL COMMENT '本月涨幅',
                                       `up_this_year` float DEFAULT NULL COMMENT '今年涨幅',
                                       `up_last_month` float DEFAULT NULL COMMENT '近一月涨幅',
                                       `up_past_year` float DEFAULT NULL COMMENT '近一年涨幅',
                                       PRIMARY KEY (`id`),
                                       KEY `idx_stock_price_ranking_stock_name` (`stock_name`),
                                       KEY `idx_stock_price_ranking_increase_precent` (`increase_precent`),
                                       KEY `idx_stock_price_ranking_increase_speed` (`increase_speed`),
                                       KEY `idx_stock_price_ranking_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin